#!/usr/bin/env python3
"""
UI Smoke Test

Verifies that ui/results.html:
1. Exists and was generated by run.py
2. Contains inlined pipeline data
3. Has records that would render in a browser
4. Is self-contained (no fetch() required for data)

Usage:
    python3 break/test_ui_smoke.py
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def test_file_exists():
    path = os.path.join(ROOT, "ui", "results.html")
    if not os.path.exists(path):
        print("  ❌ ui/results.html does not exist")
        print("     Run: python3 run.py")
        return False, None
    size = os.path.getsize(path)
    print(f"  ✅ ui/results.html exists ({size // 1024}KB)")
    return True, path


def test_inlined_data(path):
    with open(path, encoding="utf-8") as f:
        html = f.read()

    # Extract the records JSON
    records_match = re.search(
        r'window\.__PIPELINE_RECORDS\s*=\s*(\[.*?\]);\s*\n',
        html,
        re.DOTALL
    )
    if not records_match:
        print("  ❌ No inlined __PIPELINE_RECORDS found")
        return False, [], {}

    summary_match = re.search(
        r'window\.__PIPELINE_SUMMARY\s*=\s*(\{.*?\});\s*\n',
        html,
        re.DOTALL
    )
    if not summary_match:
        print("  ❌ No inlined __PIPELINE_SUMMARY found")
        return False, [], {}

    try:
        records = json.loads(records_match.group(1))
        summary = json.loads(summary_match.group(1))
    except json.JSONDecodeError as e:
        print(f"  ❌ Inlined JSON is malformed: {e}")
        return False, [], {}

    print(f"  ✅ Inlined data: {len(records)} records, summary present")
    return True, records, summary


def test_records_renderable(records):
    if not records:
        print("  ❌ No records to render")
        return False

    required_fields = ["account_id", "narrative", "classified_type"]
    missing = []
    for field in required_fields:
        if not any(r.get(field) for r in records):
            missing.append(field)

    if missing:
        print(f"  ❌ Records missing required fields: {missing}")
        return False

    with_letters = [r for r in records if r.get("draft_letter")]
    with_review = [r for r in records if r.get("review_findings") is not None]
    with_annotations = [r for r in records if r.get("consumer_annotations")]

    print(f"  ✅ Records renderable:")
    print(f"     {len(records)} total, {len(with_letters)} with letters, "
          f"{len(with_review)} reviewed, {len(with_annotations)} annotated")

    if not with_letters:
        print("  ⚠  No letters drafted — letter panel will be empty")

    return True


def test_no_fetch_required(path):
    """Verify the loadData function checks inlined data first."""
    with open(path, encoding="utf-8") as f:
        html = f.read()

    if "window.__PIPELINE_RECORDS" not in html:
        print("  ❌ loadData does not check for inlined data")
        return False

    # Verify the check comes before fetch()
    inline_check_pos = html.find("__PIPELINE_RECORDS")
    fetch_pos = html.find("fetch(")
    if inline_check_pos > fetch_pos:
        print("  ❌ Inlined data check comes AFTER fetch — will still fail on file://")
        return False

    print("  ✅ Inlined data loads before fetch — works on file://")
    return True


def test_html_structure(path):
    """Basic HTML structure checks."""
    with open(path, encoding="utf-8") as f:
        html = f.read()

    checks = [
        ("<!DOCTYPE html>", "DOCTYPE declaration"),
        ("<html", "html tag"),
        ("</html>", "closing html tag"),
        ("record-list", "record list container"),
        ("source-panel", "source panel"),
        ("letter-panel", "letter panel"),
        ("tab-review", "review tab"),
        ("tab-consumer", "consumer tab"),
        ("tab-intent", "intent tab"),
        ("selectRecord", "selectRecord function"),
        ("renderList", "renderList function"),
    ]

    all_pass = True
    for needle, label in checks:
        if needle not in html:
            print(f"  ❌ Missing: {label}")
            all_pass = False

    if all_pass:
        print("  ✅ HTML structure intact (all UI elements present)")
    return all_pass


if __name__ == "__main__":
    print("=" * 50)
    print("  UI SMOKE TEST")
    print("=" * 50)

    results = {}

    # Test 1: File exists
    exists, path = test_file_exists()
    results["file_exists"] = exists
    if not exists:
        print("\n  Run 'python3 run.py' first to generate ui/results.html")
        sys.exit(1)

    # Test 2: Inlined data
    has_data, records, summary = test_inlined_data(path)
    results["inlined_data"] = has_data

    # Test 3: Records renderable
    results["records_renderable"] = test_records_renderable(records)

    # Test 4: No fetch required
    results["no_fetch_required"] = test_no_fetch_required(path)

    # Test 5: HTML structure
    results["html_structure"] = test_html_structure(path)

    print("\n" + "=" * 50)
    print("  RESULTS")
    print("=" * 50)
    all_pass = True
    for name, passed in results.items():
        status = "✅ PASS" if passed else "❌ FAIL"
        print(f"  {name}: {status}")
        if not passed:
            all_pass = False

    if all_pass:
        print("\n  UI will render from file:// with no server needed.")
        print("  Safe to double-click on stage.")
    else:
        print("\n  ⚠ UI has issues. Fix before rehearsal.")

    sys.exit(0 if all_pass else 1)
